import { DestinationType } from '../../common/enums';

export interface DestinationSeed {
  name: string;
  type: DestinationType;
  continent: string;
  countryCode?: string;
  currency?: string;
  timezone?: string;
  bestTimeToVisit?: string;
  description?: string;
  cities?: Omit<DestinationSeed, 'cities' | 'continent' | 'countryCode'>[];
}

export const destinationData: DestinationSeed[] = [
  // ── Asia ──────────────────────────────────────────────────────────────────
  {
    name: 'Thailand',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'TH',
    currency: 'THB',
    timezone: 'Asia/Bangkok',
    bestTimeToVisit: 'November to April',
    description: 'The Land of Smiles — stunning temples, tropical beaches, and vibrant street food.',
    cities: [
      { name: 'Bangkok', type: DestinationType.CITY, bestTimeToVisit: 'November to February', description: 'Buzzing capital with grand palaces, floating markets, and legendary nightlife.' },
      { name: 'Phuket', type: DestinationType.CITY, bestTimeToVisit: 'November to April', description: 'Thailand\'s largest island known for clear waters and vibrant beach clubs.' },
      { name: 'Chiang Mai', type: DestinationType.CITY, bestTimeToVisit: 'November to February', description: 'Cultural hub of northern Thailand with ancient temples and elephant sanctuaries.' },
      { name: 'Pattaya', type: DestinationType.CITY, bestTimeToVisit: 'November to January', description: 'Coastal resort city with beaches, water parks, and lively entertainment.' },
      { name: 'Krabi', type: DestinationType.CITY, bestTimeToVisit: 'November to April', description: 'Dramatic limestone cliffs, turquoise waters, and pristine island-hopping.' },
      { name: 'Koh Samui', type: DestinationType.CITY, bestTimeToVisit: 'February to October', description: 'Tropical island with coconut groves, coral reefs, and luxury resorts.' },
    ],
  },
  {
    name: 'Indonesia',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'ID',
    currency: 'IDR',
    timezone: 'Asia/Jakarta',
    bestTimeToVisit: 'April to October',
    description: 'An archipelago of 17,000+ islands offering volcanic landscapes, ancient culture, and world-class surf.',
    cities: [
      { name: 'Bali', type: DestinationType.CITY, bestTimeToVisit: 'April to October', description: 'Island of the Gods — rice terraces, sacred temples, and surf beaches.' },
      { name: 'Jakarta', type: DestinationType.CITY, bestTimeToVisit: 'May to September', description: 'Sprawling megacity and Indonesia\'s vibrant capital.' },
      { name: 'Yogyakarta', type: DestinationType.CITY, bestTimeToVisit: 'April to October', description: 'Cultural heart of Java, gateway to Borobudur and Prambanan temples.' },
      { name: 'Lombok', type: DestinationType.CITY, bestTimeToVisit: 'May to October', description: 'Pristine beaches and the majestic Mount Rinjani volcano.' },
      { name: 'Komodo Island', type: DestinationType.CITY, bestTimeToVisit: 'April to June', description: 'Home to the legendary Komodo dragons and stunning pink beach.' },
      { name: 'Raja Ampat', type: DestinationType.CITY, bestTimeToVisit: 'October to April', description: 'Remote paradise with the world\'s highest marine biodiversity.' },
    ],
  },
  {
    name: 'India',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'IN',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    bestTimeToVisit: 'October to March',
    description: 'An ancient civilisation of diverse cultures, historic monuments, and incredible landscapes.',
    cities: [
      { name: 'Goa', type: DestinationType.CITY, bestTimeToVisit: 'November to February', description: 'Sun-kissed beaches, Portuguese heritage, and vibrant nightlife.' },
      { name: 'Mumbai', type: DestinationType.CITY, bestTimeToVisit: 'November to February', description: 'City of dreams — Bollywood, colonial architecture, and coastal promenades.' },
      { name: 'Delhi', type: DestinationType.CITY, bestTimeToVisit: 'October to March', description: 'Capital blending Mughal grandeur with modern cosmopolitan energy.' },
      { name: 'Rajasthan', type: DestinationType.CITY, bestTimeToVisit: 'October to March', description: 'Land of kings — desert forts, colourful bazaars, and camel safaris.' },
      { name: 'Kerala', type: DestinationType.CITY, bestTimeToVisit: 'September to March', description: 'Backwaters, tea plantations, Ayurveda, and lush Western Ghats.' },
      { name: 'Agra', type: DestinationType.CITY, bestTimeToVisit: 'October to March', description: 'Home of the iconic Taj Mahal and Mughal-era architecture.' },
      { name: 'Varanasi', type: DestinationType.CITY, bestTimeToVisit: 'October to March', description: 'One of the world\'s oldest cities and Hinduism\'s holiest site on the Ganges.' },
    ],
  },
  {
    name: 'Vietnam',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'VN',
    currency: 'VND',
    timezone: 'Asia/Ho_Chi_Minh',
    bestTimeToVisit: 'February to April',
    description: 'A slender S-shaped country of emerald rice paddies, limestone karsts, and rich history.',
    cities: [
      { name: 'Hanoi', type: DestinationType.CITY, bestTimeToVisit: 'September to November', description: 'Thousand-year-old capital with French colonial buildings and street food culture.' },
      { name: 'Ho Chi Minh City', type: DestinationType.CITY, bestTimeToVisit: 'December to April', description: 'Pulsating southern metropolis formerly known as Saigon.' },
      { name: 'Da Nang', type: DestinationType.CITY, bestTimeToVisit: 'February to May', description: 'Coastal city between Hanoi and Ho Chi Minh, gateway to Hoi An and Ba Na Hills.' },
      { name: 'Hoi An', type: DestinationType.CITY, bestTimeToVisit: 'February to April', description: 'UNESCO-listed ancient town of lantern-lit streets and tailored fashion.' },
      { name: 'Ha Long Bay', type: DestinationType.CITY, bestTimeToVisit: 'April to June', description: 'Iconic emerald bay of 1,600 limestone islands and islets.' },
      { name: 'Hue', type: DestinationType.CITY, bestTimeToVisit: 'January to August', description: 'Imperial capital with royal citadels, mausoleums, and refined cuisine.' },
    ],
  },
  {
    name: 'Japan',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'JP',
    currency: 'JPY',
    timezone: 'Asia/Tokyo',
    bestTimeToVisit: 'March to May, September to November',
    description: 'Where ancient traditions meet cutting-edge modernity — cherry blossoms, samurai history, and ramen.',
    cities: [
      { name: 'Tokyo', type: DestinationType.CITY, bestTimeToVisit: 'March to May', description: 'Hyper-modern capital blending neon-lit streets with tranquil shrines.' },
      { name: 'Osaka', type: DestinationType.CITY, bestTimeToVisit: 'March to May', description: 'Street food capital known for takoyaki, dotonbori, and castle ruins.' },
      { name: 'Kyoto', type: DestinationType.CITY, bestTimeToVisit: 'March to May', description: 'Japan\'s cultural heartland of 1,600 Buddhist temples and geisha districts.' },
      { name: 'Hokkaido', type: DestinationType.CITY, bestTimeToVisit: 'December to February', description: 'Powder snow skiing, lavender fields, and fresh seafood.' },
      { name: 'Hiroshima', type: DestinationType.CITY, bestTimeToVisit: 'March to May', description: 'City of peace, resilience, and the iconic Atomic Bomb Dome.' },
    ],
  },
  {
    name: 'Singapore',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'SG',
    currency: 'SGD',
    timezone: 'Asia/Singapore',
    bestTimeToVisit: 'February to April',
    description: 'A dazzling city-state of futuristic gardens, world-class food, and multicultural harmony.',
    cities: [
      { name: 'Marina Bay', type: DestinationType.CITY, description: 'Iconic skyline, Gardens by the Bay, and the famous Sands SkyPark.' },
      { name: 'Sentosa', type: DestinationType.CITY, description: 'Resort island with Universal Studios, beaches, and casino.' },
    ],
  },
  {
    name: 'Malaysia',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'MY',
    currency: 'MYR',
    timezone: 'Asia/Kuala_Lumpur',
    bestTimeToVisit: 'December to February',
    description: 'Rainforest adventures, Petronas Towers, and some of Asia\'s best street food.',
    cities: [
      { name: 'Kuala Lumpur', type: DestinationType.CITY, bestTimeToVisit: 'December to February', description: 'Gleaming capital city, home to the iconic Petronas Twin Towers.' },
      { name: 'Penang', type: DestinationType.CITY, bestTimeToVisit: 'December to February', description: 'George Town\'s UNESCO heritage streets and legendary hawker food.' },
      { name: 'Langkawi', type: DestinationType.CITY, bestTimeToVisit: 'November to April', description: 'Duty-free island archipelago of mangroves, waterfalls, and beaches.' },
      { name: 'Borneo (Sabah)', type: DestinationType.CITY, bestTimeToVisit: 'March to October', description: 'Orangutans, diving, and Mount Kinabalu in Malaysian Borneo.' },
    ],
  },
  {
    name: 'Maldives',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'MV',
    currency: 'MVR',
    timezone: 'Indian/Maldives',
    bestTimeToVisit: 'November to April',
    description: 'Overwater bungalows, crystal-clear lagoons, and the world\'s finest coral reefs.',
    cities: [
      { name: 'Malé', type: DestinationType.CITY, description: 'Compact and colourful capital island packed with mosques and markets.' },
      { name: 'North Malé Atoll', type: DestinationType.CITY, description: 'Luxury resort hub closest to the airport.' },
      { name: 'Baa Atoll', type: DestinationType.CITY, description: 'UNESCO Biosphere Reserve famous for manta rays and whale sharks.' },
    ],
  },
  {
    name: 'Sri Lanka',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'LK',
    currency: 'LKR',
    timezone: 'Asia/Colombo',
    bestTimeToVisit: 'December to March',
    description: 'The Pearl of the Indian Ocean — ancient temples, wild elephants, tea highlands, and surf beaches.',
    cities: [
      { name: 'Colombo', type: DestinationType.CITY, description: 'Bustling port capital with colonial architecture and vibrant food scene.' },
      { name: 'Sigiriya', type: DestinationType.CITY, description: 'Ancient rock fortress rising dramatically above the jungle.' },
      { name: 'Galle', type: DestinationType.CITY, description: 'Dutch colonial fort city on the southern coast.' },
      { name: 'Ella', type: DestinationType.CITY, description: 'Cool hill-country retreat with scenic train rides and waterfalls.' },
    ],
  },
  {
    name: 'Nepal',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'NP',
    currency: 'NPR',
    timezone: 'Asia/Kathmandu',
    bestTimeToVisit: 'October to November, March to May',
    description: 'Home of Everest — trekking, Buddhism, ancient Kathmandu, and breathtaking Himalayan vistas.',
    cities: [
      { name: 'Kathmandu', type: DestinationType.CITY, description: 'Ancient capital of temples, stupas, and Himalayan gateway.' },
      { name: 'Pokhara', type: DestinationType.CITY, description: 'Lakeside city surrounded by Annapurna range — trekking base camp.' },
      { name: 'Chitwan', type: DestinationType.CITY, description: 'National park safaris to spot rhinos, tigers, and crocodiles.' },
    ],
  },
  {
    name: 'Philippines',
    type: DestinationType.COUNTRY,
    continent: 'Asia',
    countryCode: 'PH',
    currency: 'PHP',
    timezone: 'Asia/Manila',
    bestTimeToVisit: 'November to May',
    description: '7,641 islands of white-sand beaches, world-class diving, and warm Filipino hospitality.',
    cities: [
      { name: 'Manila', type: DestinationType.CITY, description: 'Historic capital of Intramuros, Rizal Park, and vibrant nightlife.' },
      { name: 'Cebu', type: DestinationType.CITY, description: 'Queen City of the South — whale sharks, beaches, and waterfalls.' },
      { name: 'Palawan', type: DestinationType.CITY, bestTimeToVisit: 'November to May', description: 'El Nido\'s hidden lagoons, Puerto Princesa underground river — island paradise.' },
      { name: 'Boracay', type: DestinationType.CITY, bestTimeToVisit: 'November to May', description: 'World-famous White Beach with powdery sand and turquoise water.' },
    ],
  },
  // ── Europe ────────────────────────────────────────────────────────────────
  {
    name: 'France',
    type: DestinationType.COUNTRY,
    continent: 'Europe',
    countryCode: 'FR',
    currency: 'EUR',
    timezone: 'Europe/Paris',
    bestTimeToVisit: 'April to June, September to October',
    description: 'Art, cuisine, fashion, and the Eiffel Tower — the quintessential travel destination.',
    cities: [
      { name: 'Paris', type: DestinationType.CITY, description: 'The City of Light — Eiffel Tower, Louvre, Montmartre, and haute cuisine.' },
      { name: 'Nice', type: DestinationType.CITY, description: 'French Riviera gem with its famous Promenade des Anglais and azure sea.' },
      { name: 'Lyon', type: DestinationType.CITY, description: 'Gastronomic capital of France, UNESCO old town, and silk weaving heritage.' },
      { name: 'Provence', type: DestinationType.CITY, description: 'Lavender fields, vineyards, and sun-drenched villages of southern France.' },
    ],
  },
  {
    name: 'Italy',
    type: DestinationType.COUNTRY,
    continent: 'Europe',
    countryCode: 'IT',
    currency: 'EUR',
    timezone: 'Europe/Rome',
    bestTimeToVisit: 'April to June, September to October',
    description: 'Roman ruins, Renaissance art, pizza, pasta, and some of the world\'s most beautiful coasts.',
    cities: [
      { name: 'Rome', type: DestinationType.CITY, description: 'The Eternal City — Colosseum, Vatican, and 2,500 years of history.' },
      { name: 'Venice', type: DestinationType.CITY, description: 'Floating city of canals, gondolas, and ornate Byzantine architecture.' },
      { name: 'Florence', type: DestinationType.CITY, description: 'Birthplace of the Renaissance — Uffizi, David, and Duomo.' },
      { name: 'Milan', type: DestinationType.CITY, description: 'Global fashion capital with the Last Supper and stunning Duomo.' },
      { name: 'Amalfi Coast', type: DestinationType.CITY, description: 'Dramatic cliffside villages, turquoise sea, and limoncello.' },
    ],
  },
  {
    name: 'Greece',
    type: DestinationType.COUNTRY,
    continent: 'Europe',
    countryCode: 'GR',
    currency: 'EUR',
    timezone: 'Europe/Athens',
    bestTimeToVisit: 'April to June, September to October',
    description: 'Cradle of Western civilisation with dazzling island-hopping, ancient ruins, and Mediterranean cuisine.',
    cities: [
      { name: 'Athens', type: DestinationType.CITY, description: 'Historic capital beneath the Parthenon — mythology, souvlaki, and rooftop bars.' },
      { name: 'Santorini', type: DestinationType.CITY, description: 'Iconic blue-domed churches, volcanic caldera views, and magical sunsets.' },
      { name: 'Mykonos', type: DestinationType.CITY, description: 'Glamorous party island with windmills, Little Venice, and vibrant beaches.' },
      { name: 'Crete', type: DestinationType.CITY, description: 'Greece\'s largest island — Minoan palaces, gorges, and secluded beaches.' },
    ],
  },
  {
    name: 'Spain',
    type: DestinationType.COUNTRY,
    continent: 'Europe',
    countryCode: 'ES',
    currency: 'EUR',
    timezone: 'Europe/Madrid',
    bestTimeToVisit: 'March to May, September to November',
    description: 'Flamenco, tapas, Gaudí, and golden beaches — Europe\'s most passionate destination.',
    cities: [
      { name: 'Barcelona', type: DestinationType.CITY, description: 'Gaudí\'s architectural wonderland meets beach city — Sagrada Família, tapas, and more.' },
      { name: 'Madrid', type: DestinationType.CITY, description: 'Spain\'s vibrant capital of world-class art museums and lively nightlife.' },
      { name: 'Seville', type: DestinationType.CITY, description: 'Flamenco heartland with the grand Alcázar palace and Gothic cathedral.' },
      { name: 'Ibiza', type: DestinationType.CITY, description: 'World\'s party capital by night, secluded coves and clear water by day.' },
    ],
  },
  // ── Middle East ───────────────────────────────────────────────────────────
  {
    name: 'UAE',
    type: DestinationType.COUNTRY,
    continent: 'Middle East',
    countryCode: 'AE',
    currency: 'AED',
    timezone: 'Asia/Dubai',
    bestTimeToVisit: 'November to March',
    description: 'Futuristic skylines, golden deserts, world-record attractions, and luxury at every turn.',
    cities: [
      { name: 'Dubai', type: DestinationType.CITY, description: 'City of superlatives — Burj Khalifa, Palm Jumeirah, and world-class malls.' },
      { name: 'Abu Dhabi', type: DestinationType.CITY, description: 'Capital with the stunning Sheikh Zayed Grand Mosque and F1 Grand Prix.' },
    ],
  },
  // ── Africa ────────────────────────────────────────────────────────────────
  {
    name: 'Morocco',
    type: DestinationType.COUNTRY,
    continent: 'Africa',
    countryCode: 'MA',
    currency: 'MAD',
    timezone: 'Africa/Casablanca',
    bestTimeToVisit: 'March to May, September to November',
    description: 'Ancient medinas, Sahara dunes, riads, and the world\'s most sensory souks.',
    cities: [
      { name: 'Marrakech', type: DestinationType.CITY, description: 'The Red City — Jemaa el-Fna, spice souks, and ornate palaces.' },
      { name: 'Chefchaouen', type: DestinationType.CITY, description: 'The enchanting Blue City nestled in the Rif Mountains.' },
      { name: 'Fes', type: DestinationType.CITY, description: 'UNESCO-listed medieval medina, tanneries, and Islamic architecture.' },
    ],
  },
  // ── Americas ──────────────────────────────────────────────────────────────
  {
    name: 'USA',
    type: DestinationType.COUNTRY,
    continent: 'Americas',
    countryCode: 'US',
    currency: 'USD',
    timezone: 'America/New_York',
    bestTimeToVisit: 'Varies by region',
    description: 'From NYC skylines to Grand Canyon vistas — 50 states of unmatched variety.',
    cities: [
      { name: 'New York City', type: DestinationType.CITY, description: 'The Big Apple — Times Square, Central Park, and world-class arts.' },
      { name: 'Los Angeles', type: DestinationType.CITY, description: 'Hollywood, Santa Monica beaches, and year-round sunshine.' },
      { name: 'Las Vegas', type: DestinationType.CITY, description: 'Entertainment capital of the world — casinos, shows, and Grand Canyon day trips.' },
      { name: 'Miami', type: DestinationType.CITY, description: 'Art Deco South Beach, Cuban coffee, and Latin nightlife.' },
      { name: 'Hawaii', type: DestinationType.CITY, description: 'Volcanic islands of surf, hula, lava fields, and aloha spirit.' },
    ],
  },
  {
    name: 'Mexico',
    type: DestinationType.COUNTRY,
    continent: 'Americas',
    countryCode: 'MX',
    currency: 'MXN',
    timezone: 'America/Mexico_City',
    bestTimeToVisit: 'December to April',
    description: 'Ancient Maya ruins, turquoise Caribbean beaches, tequila, and incredible street food.',
    cities: [
      { name: 'Cancún', type: DestinationType.CITY, description: 'Caribbean resort strip with all-inclusive resorts, cenotes, and Chichén Itzá nearby.' },
      { name: 'Mexico City', type: DestinationType.CITY, description: 'Vast, vibrant megalopolis of Aztec ruins, world-class food, and street art.' },
      { name: 'Tulum', type: DestinationType.CITY, description: 'Bohemian beach town with cliff-top Maya ruins and cenote swimming.' },
    ],
  },
  // ── Oceania ───────────────────────────────────────────────────────────────
  {
    name: 'Australia',
    type: DestinationType.COUNTRY,
    continent: 'Oceania',
    countryCode: 'AU',
    currency: 'AUD',
    timezone: 'Australia/Sydney',
    bestTimeToVisit: 'September to November, March to May',
    description: 'Opera House icons, Great Barrier Reef, outback adventures, and world-class wine.',
    cities: [
      { name: 'Sydney', type: DestinationType.CITY, description: 'Harbour City of Opera House, Bondi Beach, and vibrant café culture.' },
      { name: 'Melbourne', type: DestinationType.CITY, description: 'Coffee-obsessed cultural capital known for laneways, arts, and food.' },
      { name: 'Cairns', type: DestinationType.CITY, description: 'Gateway to the Great Barrier Reef and Daintree Rainforest.' },
      { name: 'Gold Coast', type: DestinationType.CITY, description: 'Sun, surf, theme parks, and the Surfers Paradise strip.' },
    ],
  },
];
