import { SubscriptionPlanType, BillingPeriod, CreatorTier } from '../../common/enums';

export const subscriptionPlanData = [
  // ── Creator Tiers ─────────────────────────────────────────────────────────
  {
    name: 'Creator Basic',
    description: 'Perfect for getting started. List up to 5 products and grow your audience.',
    type: SubscriptionPlanType.CREATOR_TIER,
    billingPeriod: BillingPeriod.MONTHLY,
    price: 0,
    currency: 'INR',
    creatorTier: CreatorTier.BASIC,
    maxProducts: 5,
    maxContent: 20,
    commissionRate: 15,
    isActive: true,
    trialDays: 0,
    features: {
      customStorefront: false,
      analytics: 'basic',
      prioritySupport: false,
      verifiedBadge: false,
      featuredListing: false,
      bulkUpload: false,
      stripePayout: true,
    },
  },
  {
    name: 'Creator Pro – Monthly',
    description: 'Grow faster with advanced analytics, 25 products, and lower commission.',
    type: SubscriptionPlanType.CREATOR_TIER,
    billingPeriod: BillingPeriod.MONTHLY,
    price: 999,
    currency: 'INR',
    creatorTier: CreatorTier.PRO,
    maxProducts: 25,
    maxContent: 100,
    commissionRate: 10,
    isActive: true,
    trialDays: 14,
    features: {
      customStorefront: true,
      analytics: 'advanced',
      prioritySupport: false,
      verifiedBadge: false,
      featuredListing: true,
      bulkUpload: true,
      stripePayout: true,
    },
  },
  {
    name: 'Creator Pro – Yearly',
    description: 'Save 17% with annual billing. All Pro features included.',
    type: SubscriptionPlanType.CREATOR_TIER,
    billingPeriod: BillingPeriod.YEARLY,
    price: 9999,
    currency: 'INR',
    creatorTier: CreatorTier.PRO,
    maxProducts: 25,
    maxContent: 100,
    commissionRate: 10,
    isActive: true,
    trialDays: 14,
    features: {
      customStorefront: true,
      analytics: 'advanced',
      prioritySupport: false,
      verifiedBadge: false,
      featuredListing: true,
      bulkUpload: true,
      stripePayout: true,
    },
  },
  {
    name: 'Creator Premium – Monthly',
    description: 'Unlimited products, priority support, verified badge, and the lowest commission.',
    type: SubscriptionPlanType.CREATOR_TIER,
    billingPeriod: BillingPeriod.MONTHLY,
    price: 2499,
    currency: 'INR',
    creatorTier: CreatorTier.PREMIUM,
    maxProducts: null,
    maxContent: null,
    commissionRate: 7,
    isActive: true,
    trialDays: 14,
    features: {
      customStorefront: true,
      analytics: 'full',
      prioritySupport: true,
      verifiedBadge: true,
      featuredListing: true,
      bulkUpload: true,
      stripePayout: true,
      dedicatedAccountManager: false,
      apiAccess: false,
    },
  },
  {
    name: 'Creator Premium – Yearly',
    description: 'Save 17% with annual billing. All Premium features included.',
    type: SubscriptionPlanType.CREATOR_TIER,
    billingPeriod: BillingPeriod.YEARLY,
    price: 24999,
    currency: 'INR',
    creatorTier: CreatorTier.PREMIUM,
    maxProducts: null,
    maxContent: null,
    commissionRate: 7,
    isActive: true,
    trialDays: 14,
    features: {
      customStorefront: true,
      analytics: 'full',
      prioritySupport: true,
      verifiedBadge: true,
      featuredListing: true,
      bulkUpload: true,
      stripePayout: true,
      dedicatedAccountManager: true,
      apiAccess: true,
    },
  },
  // ── User Subscriptions ────────────────────────────────────────────────────
  {
    name: 'Traveller Premium – Monthly',
    description: 'Ad-free discovery, offline itineraries, and exclusive creator content.',
    type: SubscriptionPlanType.USER_PREMIUM,
    billingPeriod: BillingPeriod.MONTHLY,
    price: 299,
    currency: 'INR',
    creatorTier: null,
    maxProducts: null,
    maxContent: null,
    commissionRate: null,
    isActive: true,
    trialDays: 7,
    features: {
      adFree: true,
      offlineItineraries: true,
      exclusiveContent: true,
      earlyAccess: false,
      concierge: false,
    },
  },
  {
    name: 'Traveller Premium – Yearly',
    description: 'Save 16% annually. All Premium Traveller features included.',
    type: SubscriptionPlanType.USER_PREMIUM,
    billingPeriod: BillingPeriod.YEARLY,
    price: 2999,
    currency: 'INR',
    creatorTier: null,
    maxProducts: null,
    maxContent: null,
    commissionRate: null,
    isActive: true,
    trialDays: 7,
    features: {
      adFree: true,
      offlineItineraries: true,
      exclusiveContent: true,
      earlyAccess: true,
      concierge: false,
    },
  },
];
